version: '3.2'

services:

  web:
    image: node:14.7.0
    working_dir: /srv
    container_name: web
    command: tail -f /dev/null
    env_file: 
      - .env
    ports:
      - "8080:8080"
    links:
      - db
    volumes:
      - type: bind
        source: ./srv
        target: /srv

  db:
    image: mongo:4.4
    container_name: db
    volumes:
      - type: volume
        source: mongodb
        target: /data/db
      - type: volume
        source: mongodb_config
        target: /data/configdb
    ports:
      - 27018:27017
    command: mongod

volumes:
  srv:

  mongodb:
  mongodb_config:
