version: '3.2'

services:

  # web is set up with everything in the Dockerfile so the only thing 
  # done here is the external port is bound to the one already configured 
  # for the docker instance
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    env_file: 
      - .env
    ports:
      - "8080:8080"
    links:
      - db

  db:
    image: mongo:4.4
    container_name: db
    volumes:
      - type: volume
        source: mongodb
        target: /data/db
      - type: volume
        source: mongodb_config
        target: /data/configdb
      #- mongodb:/data/db
      #- mongodb_config:/data/configdb
    ports:
      - 27018:27017
    command: mongod

volumes:
  mongodb:
  mongodb_config:
